package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;


public class Capturar extends javax.swing.JFrame {

   
    public Capturar() {
        initComponents();
        setTitle("Capturar datos");
        setResizable(false);
        setLocationRelativeTo(null);
        
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
          ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField_Cliente_id = new javax.swing.JTextField();
        jTextField_Cliente_nombre = new javax.swing.JTextField();
        jTextField_Articulo_Id = new javax.swing.JTextField();
        jTextField_Articulo_nombre = new javax.swing.JTextField();
        jTextField_Articulo_Costo = new javax.swing.JTextField();
        jTextField_Articulo_Venta = new javax.swing.JTextField();
        jTextField_Venta_Id = new javax.swing.JTextField();
        jTextField_Venta_Fecha = new javax.swing.JTextField();
        jTextField_Venta_Costo = new javax.swing.JTextField();
        jTextField_Venta_Venta = new javax.swing.JTextField();
        jTextField_Encuesta_fecha = new javax.swing.JTextField();
        jTextField_Encuesta_Idventa = new javax.swing.JTextField();
        jComboBox_Satisfaccion = new javax.swing.JComboBox<>();
        ButtonCapturarDatos = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Capturar Datos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Encuesta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Venta");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cliente");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Articulo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Id: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Costo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Venta: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Costo: ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Venta: ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Id venta: ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Fecha: ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Satisfacción:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 100, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Id: ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jTextField_Cliente_id.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField_Cliente_id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Cliente_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cliente_idActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Cliente_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 130, -1));

        jTextField_Cliente_nombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField_Cliente_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Cliente_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cliente_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Cliente_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 130, -1));

        jTextField_Articulo_Id.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField_Articulo_Id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Articulo_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Articulo_IdActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Articulo_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 130, -1));

        jTextField_Articulo_nombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField_Articulo_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Articulo_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Articulo_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Articulo_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 130, -1));

        jTextField_Articulo_Costo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField_Articulo_Costo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Articulo_Costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Articulo_CostoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Articulo_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 130, -1));

        jTextField_Articulo_Venta.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField_Articulo_Venta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Articulo_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Articulo_VentaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Articulo_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 130, -1));

        jTextField_Venta_Id.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField_Venta_Id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Venta_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Venta_IdActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Venta_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 130, -1));

        jTextField_Venta_Fecha.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField_Venta_Fecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Venta_Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Venta_FechaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Venta_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 130, -1));

        jTextField_Venta_Costo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField_Venta_Costo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Venta_Costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Venta_CostoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Venta_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 130, -1));

        jTextField_Venta_Venta.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField_Venta_Venta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Venta_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Venta_VentaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Venta_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 130, -1));

        jTextField_Encuesta_fecha.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField_Encuesta_fecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Encuesta_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Encuesta_fechaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Encuesta_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 130, -1));

        jTextField_Encuesta_Idventa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField_Encuesta_Idventa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Encuesta_Idventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Encuesta_IdventaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Encuesta_Idventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 130, -1));

        jComboBox_Satisfaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Satisfecho", "No satisfecho", " " }));
        jComboBox_Satisfaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SatisfaccionActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Satisfaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, -1, -1));

        ButtonCapturarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        ButtonCapturarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCapturarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCapturarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 160, 150));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Cliente_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cliente_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Cliente_nombreActionPerformed

    private void jTextField_Articulo_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Articulo_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Articulo_IdActionPerformed

    private void jTextField_Articulo_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Articulo_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Articulo_nombreActionPerformed

    private void jTextField_Articulo_CostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Articulo_CostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Articulo_CostoActionPerformed

    private void jTextField_Articulo_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Articulo_VentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Articulo_VentaActionPerformed

    private void jTextField_Venta_FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Venta_FechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Venta_FechaActionPerformed

    private void jTextField_Cliente_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cliente_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Cliente_idActionPerformed

    private void jTextField_Venta_CostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Venta_CostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Venta_CostoActionPerformed

    private void jTextField_Venta_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Venta_VentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Venta_VentaActionPerformed

    private void jTextField_Encuesta_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Encuesta_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Encuesta_fechaActionPerformed

    private void jTextField_Encuesta_IdventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Encuesta_IdventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Encuesta_IdventaActionPerformed

    private void jTextField_Venta_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Venta_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Venta_IdActionPerformed

    private void jComboBox_SatisfaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SatisfaccionActionPerformed
        String satisfaccion;
        satisfaccion = jComboBox_Satisfaccion.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox_SatisfaccionActionPerformed

    private void ButtonCapturarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCapturarDatosActionPerformed

        
    }//GEN-LAST:event_ButtonCapturarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Capturar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCapturarDatos;
    private javax.swing.JComboBox<String> jComboBox_Satisfaccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField jTextField_Articulo_Costo;
    private javax.swing.JTextField jTextField_Articulo_Id;
    private javax.swing.JTextField jTextField_Articulo_Venta;
    private javax.swing.JTextField jTextField_Articulo_nombre;
    private javax.swing.JTextField jTextField_Cliente_id;
    private javax.swing.JTextField jTextField_Cliente_nombre;
    private javax.swing.JTextField jTextField_Encuesta_Idventa;
    private javax.swing.JTextField jTextField_Encuesta_fecha;
    private javax.swing.JTextField jTextField_Venta_Costo;
    private javax.swing.JTextField jTextField_Venta_Fecha;
    private javax.swing.JTextField jTextField_Venta_Id;
    private javax.swing.JTextField jTextField_Venta_Venta;
    // End of variables declaration//GEN-END:variables
}
